import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Providers from '@/app/providers';
import Link from 'next/link';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={
          inter.className + ' m-auto bg-blue-50 min-h-screen min-w-screen'
        }>
        <nav className="h-16 w-full bg-blue-200 flex flex-row items-center justify-around">
          <div>
            <Link href={'/'} className="text-black font-normal underline">
              Home
            </Link>
          </div>
          <div>
            <Link href={'/'}>
              <h1 className="text-2xl font-bold text-center text-blue-900 tracking-widest">
                BookGalab
              </h1>
            </Link>
          </div>
          <div></div>
        </nav>
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
